import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./providers";
import Header from "./components/headerFooter/header";
import Footer from "./components/headerFooter/footer";

const inter = Inter({ subsets: ["latin"] });

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${inter.className} bg-stone-800 `}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}
