import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./providers";
import Header from "./components/headerFooter/header";
import Footer from "./components/headerFooter/footer";

const inter = Inter({ subsets: ["latin"] });

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${inter.className} bg-stone-700`}>
          <Header />
          <main className="min-h-screen">{children}</main>

          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
}
